project_id = "lpcviyjdsgghvuddthxr"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54328
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54329
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true

[edge_runtime]
enabled = true
port = 54330
inspector_port = 54331

[functions.gps51-auth]
verify_jwt = false

[functions.gps51-realtime-ws]
verify_jwt = false

[functions.gps51-sync]
verify_jwt = false

[functions.gps51-proxy]
verify_jwt = false